config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :cheques, only: %i[show new]

  root 'cheques#index'
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/cheques_controller.rb
# frozen_string_literal: true

class ChequesController < ApplicationController
  def index; end

  def new; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/application/_balance.html.haml
:ruby
  active_balance_link ||= false
  balance_container_extra_classes ||= ''
  balance_container_id ||= nil
  data ||= nil
  label ||= 'Balance'
  label_glyph_classes ||= nil
  hide_connect_button ||= false
  user_wallet_balance ||= false

= render 'polkadot_connect_button_small' unless hide_connect_button
= tag.div(class: "balance-container #{balance_container_extra_classes} d-none #{user_wallet_balance ? 'user-balance-container' : ''}", data:, id: balance_container_id) do
  - if label_glyph_classes
    %em{ class: label_glyph_classes }
  - if label.present?
    #{label}:
  // This could be the button loading part...
  = render 'loading', tag_name: :span do
    - if active_balance_link
      %a.balance{ href: '#' }
    - else
      %span.balance
    %span.balance-as-usd

app/views/application/_button_loading.html.haml
:ruby
  button_type ||= 'button'
  data ||= nil
  ready_label ||= nil
  icon_only ||= false
  button_id ||= nil

= render 'loading', tag_type: button_type, data:, ready_label:, icon_only:, tag_classes: button_classes, tag_id: button_id do
  = ready_label || yield

app/views/application/_footer.html.haml
%footer.footer.d-flex.align-items-center
  .container-fluid
    .row
      .col-12.d-flex.justify-content-between
        = link_to 'https://btn.group', target: '_blank', rel: 'noopener' do
          = image_tag 'https://res.cloudinary.com/hv5cxagki/image/upload/c_scale,dpr_2,f_auto,h_30,q_auto/v1/branding/black-with-text_jrkb7u_i1xuow_ii0vtw.png', class: 'logo logo-dark'
          = image_tag 'https://res.cloudinary.com/hv5cxagki/image/upload/c_scale,dpr_2,f_auto,h_30,q_auto/v1/branding/logo_plus_text_1_fitfuq_uqsgxw.png', class: 'logo logo-light'
        .text-end

app/views/application/_header.html.haml
%header#page-topbar
  .layout-width
    .navbar-header
      .d-flex
        .horizontal-logo
          = link_to root_path, class: 'logo logo-light' do
            .fs-2 Safe Send
        .header-item
          %button.btn.btn-icon.btn-topbar.btn-ghost-secondary.rounded-circle{ 'data-bs-target' => '#about-modal', 'data-bs-toggle' => 'modal', type: 'button' }
            %i.bx.bx-info-circle.fs-22
      .d-flex.align-items-center
        .dropdown.ms-sm-3.header-item.topbar-user
          %button.btn.d-none#page-header-user-dropdown{ 'aria-expanded' => 'false', 'aria-haspopup' => 'true', 'data-bs-toggle' => 'dropdown', type: 'button', 'data-bs-auto-close': 'outside' }
            %span.d-flex.align-items-center
              %img.user-address-alias-avatar{ alt: 'Wallet logo', src: 'https://www.pngall.com/wp-content/uploads/12/Avatar-Profile-PNG-Clipart.png', height: 40 }
              .text-start.ms-3
                .fw-medium.user-name-text.account-name
                .fs-12.user-name-sub-text.account-address-abbreviated
          .dropdown-menu.dropdown-menu-end
            %h6.dropdown-header
              .d-flex.flex-column.position-relative
                .d-flex.align-items-center
                  .wallet-address.me-2#polkadot-user-account-menu-wallet-address
                  %button.btn.btn-icon.btn-sm
                    %i.bi.bi-clipboard.text-muted.fs-4{ 'data-clipboard-target' => '#polkadot-user-account-menu-wallet-address' }
            .dropdown-divider
            = link_to 'Change', '#', id: 'change-account-link', class: 'dropdown-item'
        = render 'polkadot_connect_button'

app/views/application/_loading.html.haml
:ruby
  tag_type ||= nil
  data ||= nil
  ready_label ||= nil
  icon_only ||= false
  tag_classes ||= nil
  tag_id ||= nil
  tag_name ||= :button

= content_tag tag_name, type: tag_type, class: tag_classes, data:, id: tag_id do
  %span.d-none.loading
    %em.spinner-grow.spinner-grow-sm{ 'aria-hidden' => 'true', role: 'status' }
    - unless icon_only
      %em.loading-status Loading...
  %span.ready
    = ready_label || yield

app/views/application/_polkadot_account_list.html.haml
.modal.fade#polkadot-account-list{ 'aria-hidden' => 'true', role: 'dialog', tabindex: '-1' }
  .modal-dialog
    .modal-content
      .modal-header
        %h5.modal-title Select an account
        %button.btn-close{ 'aria-label' => 'Close', 'data-bs-dismiss' => 'modal', type: 'button' }
      .modal-body
        .list-group.overflow-auto

app/views/application/_polkadot_connect_button.html.haml
- extra_button_classes ||= 'btn-primary'

= render 'button_loading', button_classes: "btn d-none polkadot-connect-button #{extra_button_classes}" do
  Connect Wallet

app/views/application/_polkadot_connect_button_small.html.haml
- extra_button_classes ||= ''

= render 'polkadot_connect_button', extra_button_classes: "btn-light-primary border btn-sm mb-1 #{extra_button_classes}"

app/views/application/_preloader.html.haml
#preloader
  #status
    .spinner-border.text-primary.avatar-sm{ role: 'status' }
      %span.visually-hidden Loading...

app/views/application/_token_button.html.haml
- additional_button_classes ||= ''

%button.btn.dropdown-toggle.align-items-center.d-flex{ class: additional_button_classes, 'data-bs-target' => data_target, 'data-bs-toggle' => 'modal', type: 'button', id: button_id, 'data-initial-id': 0 }
  .me-2.overflow-hidden.rounded-circle{ style: 'height: 25px; width: 25px;' }
    %img{ style: 'height: 25px; width: 25px;' }
  %span.token-symbol.me-2

app/views/application/_token_list.html.haml
- include_other ||= false

.modal.fade.token-list{ 'aria-hidden' => 'true', 'aria-labelledby' => modal_title_id, role: 'dialog', tabindex: '-1', id: modal_id }
  .modal-dialog.modal-dialog-scrollable
    .modal-content{ id: modal_content_id }
      .modal-header.pb-0.border-0
        %h5.modal-title{ id: modal_title_id } Select a token
        %button.btn-close{ 'aria-label' => 'Close', 'data-bs-dismiss' => 'modal', type: 'button' }
      .modal-header.border-bottom.pt-2
        %input.form-control.search{ autocomplete: 'off', name: 'inputname1', type: 'text', placeholder: 'Search', id: modal_input_id }
      .modal-body
        .position-absolute No result found.
        .card.border-0.shadow-none.mb-0
          .list-group.list

app/views/cheques/index.html.haml
.container-fluid.polkadotjs#cheques-index
  .row.justify-content-center
    .col-12
      .card
        .card-header
          .d-flex.align-items-center
            %h5.card-title.mb-0.flex-grow-1 Cheques
            .flex-shrink-0
              .d-flex.flex-wrap.gap-2
                = link_to new_cheque_path, class: 'btn btn-primary add-btn' do
                  %i.ri-add-line.align-bottom.me-1
                  New
        .card-body
          .loading.d-none
            %em.spinner-grow.spinner-grow-sm{ 'aria-hidden' => 'true', :role => 'status' }
            %em
              %b Loading...
          .ready#cheques-container
            .table-responsive.table-card.mb-4
              %table.table.align-middle.table-nowrap.mb-0#cheques-table

app/views/cheques/new.html.haml
.container.polkadotjs#cheques-new
  .row
    .col-lg-9.col-xl-8.mx-auto.mb-5
      .card
        .card-body
          %h1.mb-4#cheques-new-form-title Safe Send
          %form.needs-validation{ name: 'chequesNewForm', novalidate: 'novalidate' }
            .mb-3
              %label.form-label.required{ for: 'cheque-to' } Pay to the order of
              %input.form-control#cheque-to{ name: 'to', required: 'required', type: 'text', placeholder: "Enter recipient's wallet address" }
              .invalid-feedback
                Invalid address.
            .mb-3
              %label.form-label AZERO.ID
              %input.form-control{ name: 'azeroId', disabled: true, type: 'text' }
            .mb-3
              = render 'balance', balance_container_extra_classes: 'form-label required', user_wallet_balance: true, active_balance_link: true, data: { input_selector_to_click_fill_to: "form[name='chequesNewForm'] input[name=amount]", smart_contract_address: '' }
              .position-relative
                %input.form-control{ name: 'amount', autocomplete: 'off', required: true, type: 'number', step: 'any', min: 0 }
                .position-absolute{ style: 'top: -1px; right: -5px;' }
                  = render 'token_button', additional_button_classes: '', button_id: 'fungible-token-button', data_target: '#fungibleTokens'
            .d-flex
              .flex-fill
                %label.form-label{ for: 'cheque-memo' } Memo
                %input.form-control#cheque-memo{ name: 'memo', type: 'text', autocomplete: 'off' }
              .d-flex.align-items-center.ms-3
                %a.btn.btn-light.me-3{ href: '/' } Cancel
                %button.btn.btn-primary{ type: 'submit' }
                  %span.d-none.loading
                    %em.spinner-grow.spinner-grow-sm{ 'aria-hidden' => 'true', role: 'status' }
                    %em.loading-status Loading...
                  %span.ready
                    Create
          .card-text.text-end
            %small.text-muted
              Fee:
              %span#fee-amount
                %em.loading-status Loading...
  = render 'token_list', modal_title_id: 'fungibleTokenLabel', modal_id: 'fungibleTokens', modal_content_id: 'token-list', modal_input_id: 'input-text-1', label_type: 'symbol'

app/views/layouts/application.html.haml
!!!
%html{ 'data-bs-theme' => 'light', 'data-layout' => 'horizontal', 'data-preloader' => 'enable', 'data-sidebar' => 'light', 'data-sidebar-image' => 'none', 'data-sidebar-size' => 'lg', 'data-topbar' => 'dark', lang: 'en' }
  %head
    %title Safe Send
    %meta{ charset: 'utf-8' }
    = favicon_link_tag 'favicon.png'
    %meta{ name: 'description', content: 'Safe Send is a decentralised payment gateway that makes it easy and safe for businesses to accept crypto on Aleph Zero. By utilising a chequeing mechanism, send/collect, it makes crypto payments forgiving enough for mass adoption.' }
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1, shrink-to-fit=no' }
    %meta{ property: 'og:image', content: 'favicon.png' }
    %meta{ property: 'og:site_name', content: 'Safe Send' }
    = csrf_meta_tags
    = csp_meta_tag

    // === CUSTOM ===
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload'

    // === DATATABLE ===
    %link{ href: 'https://cdn.datatables.net/v/dt/dt-1.13.6/datatables.min.css', rel: 'stylesheet' }
    %script{ src: 'https://cdn.datatables.net/v/dt/dt-1.13.6/datatables.min.js' }
    %script{ src: 'https://cdn.datatables.net/plug-ins/1.13.6/api/processing().js', type: 'text/javascript' }

    // === CLIPBOARD ===
    %script{ src: 'https://cdn.jsdelivr.net/npm/clipboard@2.0.11/dist/clipboard.min.js' }
  %body{ class: "rails-env-#{Rails.env}" }
    #layout-wrapper
      = render 'header'
      .main-content
        .page-content
          = yield
      = render 'footer'
    = render 'preloader'
    = render 'polkadot_account_list'
    .modal.fade#about-modal{ 'aria-hidden' => 'true', 'aria-labelledby' => 'myModalLabel', tabindex: '-1' }
      .modal-dialog.modal-xl
        .modal-content
          .modal-header
            %h5.modal-title Safe Send
            %button.btn-close{ 'aria-label' => 'Close', 'data-bs-dismiss' => 'modal', type: 'button' }
          .modal-body
            %p.text-muted Safe Send is a decentralised payment gateway that makes it easy and safe for businesses to accept crypto on Aleph Zero. By utilising a chequeing mechanism, send/collect, it makes crypto payments forgiving enough for mass adoption.
            %p.text-muted Safe Send also integrates AZERO.ID, to provide an optional, extra layer of protection. It does this by verifying that the recipient's wallet matches the provided AZERO.ID.
            %p.text-muted Safe Send is designed to fit into modern e-commerce workflows.
            .mb-10
              %h5.fs-15 Requirements
              %p.text-muted
                1. A browser extension for signing transactions such as SubWallet, Aleph Zero Signer, Polkadotjs or Talisman.
                %br
                2.
                = link_to 'TZERO', 'https://faucet.test.azero.dev/', target: '_blank', rel: 'noopener'
                for gas
            .mb-10
              %h5.fs-15 Instructions
              %p.text-muted
                1. Sender: Create cheque with recipient's address, crypto, token and memo.
                %br
                2. Sender: Tell recipient that a cheque has been created.
                %br
                3. Recipient: Review details then collect funds.
            %h5.fs-15 References
            %p.text-muted
              1.
              =link_to 'GitHub: az_safe_send', 'https://github.com/btn-group/az_safe_send', target: '_blank', rel: 'noopener'
              %br
              2.
              = link_to 'GitHub: safe_send', 'https://github.com/btn-group/safe_send', target: '_blank', rel: 'noopener'
              %br
              3.
              = link_to 'GitHub: squid_safe_send', 'https://github.com/btn-group/squid_safe_send', target: '_blank', rel: 'noopener'
              %br
              4.
              = link_to 'smartcontracthub.tech', 'https://smartcontracthub.tech', target: '_blank', rel: 'noopener'